projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: ${env:API_ENDPOINT}
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: database/prisma.yml
