version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            host: ${DB_HOST}
            port: 3306
            user: ${DB_USER}
            password: ${DB_PASSWORD}
            connectionLimit: 2
            migrations: true