version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      SLOW_QUERIES_LOGGING: 'true'
      SLOW_QUERIES_LOGGING_THRESHOLD: '0'
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_SECRET}
        port: '4466'
        databases:
          default:
            connector: mysql
            host: mysql-db
            port: 3306
            user: root
            password: prisma
            connectionLimit: 2
            migrations: true
  mysql-db:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~